language: c

sudo: required
dist: trusty

env:
  global:
   - secure: "qvRpkAmV7PRQHoUfjhykb5lkvMyMFAlNYh/1140ej/iHjDsO9bFpX2qxbfgAe8jaW8VBf4ly+VpjA9ByJHWol6/b+FwURa/yiFgNESxeYDUJz/dJCYyrgORH+t41bCwV8SEYZmpa3NJiDi4GkH8iojEi+dQYhWoN4uwEg81m45c="

compiler:
  - gcc
  - clang

before_install: chmod +x travis/*

install: travis/deps.sh

script: travis/make.sh && tail -n1000 /home/travis/build/omf2097/openomf/cov-int/build-log.txt

notifications:
  email: false

addons:
  coverity_scan:
    project:
      name: "omf2097/openomf"
      description: "One Must Fall 2097 Remake"
    notification_email: katajakasa@gmail.com
    build_command_prepend: cov-configure --gcc && cmake -DCMAKE_C_COMPILER=/usr/bin/gcc-6 -DCMAKE_BUILD_TYPE=Release -DUSE_TESTS=Off .
    build_command: make -j
    branch_pattern: coverity_scan
